register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

test:
  path: /api/get_logged
  controller: App\Controller\AuthController::getLogged

api_login_check:
  path:     /login_check
  methods:  [POST]