register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

test:
  path: /get_logged
  controller: App\Controller\AuthController::getLogged

login_check:
  path:     /login_check
  methods:  [POST]